language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: share-your-ideas-nodejs
  api_key:
    secure: cTA1OMcETLklFc/bYSWknywEr0gch9dibgJR4dH6OIb9bkf/2IxVcZ/cvDdsIq8idW3zykm6uKmTUz6r7/C5ZM3TP1y3S4QvnRh5VehensajAy73CKgliigly1lSJaw0Kzxp1s6NBUTnEWRi1TW1vLFPLFBpoB23sV1e67LH915H3opmq33RgiU9o4KeyCO48wa/pD1COMB5rVSaKTHgFWZhYhhxvOAjIv5epjFr3wfNPWV9SkvGz39ncGekXFSksYtAfdyuHDZDhKcBSxD0aT5GnkJU4OizhlCIctrt2kjvImkUCT69sa8LXYHcK/GJgjb+rb2KoNLMzDN6ygvzT3XdTA3dJ+2NRAGhAX4OkNrQJkugptPvD7+u7gDSrSbFrgjEmwynHawZ/MQMerAuMo1Ky0q8j+pveoyGLss38ZQ3LLNp46HqByaWID9Rws7mgSOt+zJxYuQewKuhrNAFkDFz7dwGR49IUCKnt7T5n/ChYY3Smfef0QKNVwHcAQE90JX+t4riQb5b2aq4IT5QnNMI7NFqKtS/5TspZ/U6vYBp9DEYLMv07sCdKvsio9c0zgDQhTI+RmaOl+VcZrMWHfd4wE288HEdXUsHpaC9J3k7ikBebXwkyV3jWBKs+L/OmxQ+ltWnKj8Dd2Nz30GMPTEmvWij/frSa+1llj9h2GY=
