language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: share-your-ideas-nodejs
  api_key:
    secure: eK/InFAQHfRboPFfB573W8cIwVmkdKP8rqN76mdRbJG7C/I/TqFIN2AdHgu38Zrb92M6oUNnmuK9xO/5+7KivZidKBCZx1o6dxghFGR2dww8BIJ2waAdbVk+vc9/Fx4O2nQsDzSJYwtPdBOzDU+kdg+QMySLSw21a+gtLO0BzI9v3vXyXEIIvSv4ateYbfJ2NyXrE7cGM0Cxx6lFuiaazRxxzNzi9r9cRA8GbLQa5OsnPStpnBr0AqAxEjV6gzke+ey5Bnho1gGNwv12jnwcqxxylnnylSGqzhD39VP2pXMcXiELdrOWlSz3nNx8xwsp9ASO83xskEhW4vwzPxPIeg8gQpTJwmxrtN1g4qlK0Sh0M3e2LUkEa5rz2ZUHY7+hF0A6MqYcHm5SNEN+9MB0vRmPtuTNXd0aPXYAyyUXVQt07fDYUwao/QzJzlnNQDrIv21gZ6h6zFT4GihDRNGUqxKnqBdVcL8Lh8qfQPl7hI0nOAHmQBRCFdK9CX65xs8/KpOfvt5bOVr1TRNVo+oWtdfOggWJ+5NNUF+Y9muLnIMFFufZzAnrXSl+EBXAjSH8gZsyadMBWr3PRoJmunPKm/TGGRN4DKbQjfxQcq1bWxCvW5+VwyqOSxTjoxmcsWbE0YzoN+IzFnkCN5+8SwwZpcqpoQoJMoCSRcqz/OsDqMI=
