language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: share-your-ideas-nodejs
  api_key:
    secure: cL4Z0s5DM1L/L7vsQynfDCJVS3CdCZun0tiqMke+yMSEaGEMfYdyOWCmS1wQlLs3GRESeYxek9h/pDvoLkCRgvaHPlAJfhMIgzWiq48S3iOW/z/xKpvysdzbOhGainwi0aOzFMfxwBHeou7Sq+AWrz5Bso1u27emFUfXYWhWkwAha+PHG8XXt0yBMx8hniwYBOZIx03djSa6Aj9229x2Flu2x6Md4MmF8+QgCzFvRTfJT7MkH9D6xS+rlNB16wcFZxrbW3oPoFMjGt8nXaqzgiSu+KRZ9Ak8Fd5QYVw0t6ITkMxMw2PTl9+QWbNHheDS1+Chjh3MO5Ga3ZxOvT+Cz681jyAKtYUcEvp61wwFNE+uaJx+oeeXWua7nxhR/OWiLrIVH3AaxeNbSLMMyKluaToeCLXEVrkSHrLGU9F860Riqj3dCGVCjTWuPvrpGBaQt2Aq6ryIaXVmYeeAuQvSOciqukznmtjCjJjz4DY6FL1ErUlsK45DBSw7drfr0vgVPfKXHGrnDZycIf0i8BNI7LxphqPV54/OnkYf/gyl7UEPf0RXKG65EbxvAvTGhCEdW4HssetJjyX2WYDGvWUeEj4OrObYqCK1Dp/K4FpljGFBIZAezIVH2HTe6EdEgLksH8+uy8y4VBqtpxx3QkNZ7sC8w8IfZM7wACm1D48ctl8=
