version: "3"

services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/shareyouridea
      - APPLICATION_NAME=Share Your Idea
      - JWT_SECRET=hjgs7gf823gf34ERFGnjksgfhsfhjd234423
      - CACHE_KEY=6723hshdgf1@?)$%%$
      - SWAGGER_DOC=swaggerDEV
    ports:
      - "5000:5000"
  mongo:
    image: mongo
